name       : libatasmart
version    : 0.19
release    : 5
source     :
    - git|git://0pointer.de/libatasmart.git : v0.19
homepage   : http://0pointer.de
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Disk reporting library
description: |
    The libatasmart package is a disk reporting library. It only supports a subset of the ATA S.M.A.R.T. functionality.
builddeps  :
    - pkgconfig(vapigen)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share/doc
