name        : libatasmart
version     : 0.19
release     : 3
source      :
    - http://0pointer.de/public/libatasmart-0.19.tar.xz : 61f0ea345f63d28ab2ff0dc352c22271661b66bf09642db3a4049ac9dbdb0f8d
homepage    : http://0pointer.de
license     : GPL-2.0
component   : desktop.library
summary     : Disk reporting library
description : |
    The libatasmart package is a disk reporting library. It only supports a subset of the ATA S.M.A.R.T. functionality.
builddeps   :
    - pkgconfig(vapigen)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share/doc
